"""
Global constants for the Study Planner App.
"""

# Priority levels
PRIORITY_HIGH = "high"
PRIORITY_MEDIUM = "medium"
PRIORITY_LOW = "low"

PRIORITY_LEVELS = [PRIORITY_HIGH, PRIORITY_MEDIUM, PRIORITY_LOW]

# Categories
CATEGORY_HOMEWORK = "homework"
CATEGORY_EXAM = "exam"
CATEGORY_PROJECT = "project"
CATEGORY_REPORT = "report"
CATEGORY_PRESENTATION = "presentation"
CATEGORY_OTHER = "other"

CATEGORIES = [
    CATEGORY_HOMEWORK,
    CATEGORY_EXAM,
    CATEGORY_PROJECT,
    CATEGORY_REPORT,
    CATEGORY_PRESENTATION,
    CATEGORY_OTHER,
]

# Assignment types for AI analysis
ASSIGNMENT_TYPE_ESSAY = "essay"
ASSIGNMENT_TYPE_REPORT = "report"
ASSIGNMENT_TYPE_PRESENTATION = "presentation"
ASSIGNMENT_TYPE_CODE = "code"
ASSIGNMENT_TYPE_GENERAL = "general"

ASSIGNMENT_TYPES = [
    ASSIGNMENT_TYPE_ESSAY,
    ASSIGNMENT_TYPE_REPORT,
    ASSIGNMENT_TYPE_PRESENTATION,
    ASSIGNMENT_TYPE_CODE,
    ASSIGNMENT_TYPE_GENERAL,
]

# Default values
DEFAULT_REMINDER_LEAD_TIME_MINUTES = 30
DEFAULT_PAGE_SIZE = 20
